services:
  - type: web
    name: back-alley-web
    env: ruby
    buildCommand: ./bin/render-build.sh
    startCommand: bin/rails server
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
    buildFilter:
      paths:
        - Gemfile*
        - yarn.lock
        - package.json
        - app/assets/**
        - app/javascript/**
        - app/stylesheets/**
        - bin/**
        - config/**
        - db/**
        - render.yaml
        - postcss.config.js
        - tailwind.config.js
